### ISSUE TITLE
Generic OIDC Provider

### ISSUE THREAD

**Issue by amoscatelli** [rwth-acis/i5-Toolkit-for-Unity#15]
**Is your feature request related to a problem? Please describe.**
Code behind Learning Layers Provider implementation is good enough to work with other oidc providers.
First of all, their cloud based solution is clearly based on Redhat Keycloak, so this proves this implementation should be ok at least with every keycloak based solution (both on premise and cloud).

For example, in my case, to make a provider compatible with my oidc provider I simply copied the whole source code from Learning Layers Provider and changed authorizationEndpoint, tokenEndpoint, userInfoEndpoint.

But I think this is wrong, why rewriting the whole implementation ?

**Describe the solution you'd like**
I suggest to create and AbstractOIDCProvider where you have to provider the issuer url and then the three endpoints are automatically computed oidc style from the .well-known endpoint (the oidc discovery document, this is what it exists for).

For example for Learning Layers this is the right endpoint :
https://auth.las2peer.org/auth/realms/main/.well-known/openid-configuration

My oidc provider exposes the same endpoint.

Thank you in advance

**Comment by BenediktHensen** [comment]
Thank you for the input! These are great ideas.

A base class definitely makes sense since many OIDC implementations will be similar to the Keycloak implementation. The initial idea for keeping them separate was that there might be more complex login flows with additional security checks along the way. For instance, the login on Google has an additional random number that is transmitted with each request and response to make sure that the client and the server are still talking about the same login session. But even with these, a generic base class would help since such special cases could just override the base implementation where needed.

We are currently working on such an abstract base class for an OIDC provider implementation. This updated implementation will then also automatically compute the endpoints from the discovery document. So, everything will get even more streamlined.

So, stay tuned for the update which will arrive shortly!

**Comment by BenediktHensen** [comment]
This is now realized and published in version 1.9.0 🚀
