### ISSUE TITLE
OpenId Connect won't work on android

### ISSUE THREAD

**Issue by Cyprotic** [rwth-acis/i5-Toolkit-for-Unity#17]
Following the documentation (https://rwth-acis.github.io/i5-Toolkit-for-Unity/1.8.1/manual/OpenID-Connect-Client.html), I was able to set up the openId connection via the unity editor but not on the android, I followed the documentation to the letter.

The strapper class:
`protected override void RegisterServices()
    {
        Debug.Log("OpenIdBootStrapper");
        OpenIDConnectService oidc = new OpenIDConnectService();
        oidc.OidcProvider = new ATSOIDCProvider();
        oidc.OidcProvider.ClientData = ATSOIDCClientData.clientData;
        // this example shows how the service can be used on an app for multiple platforms
        
        ServiceManager.RegisterService(oidc);
        #if UNITY_EDITOR
            oidc.RedirectURI = "http://127.0.0.1:8080";
            ServiceManager.GetService<OpenIDConnectService>().ServerListener.ListeningUri = "http://127.0.0.1:8080";
        #endif
        #if !UNITY_EDITOR
            oidc.RedirectURI = "OURURI";
            DeepLinkingService service = new DeepLinkingService();
            ServiceManager.RegisterService(service);
            service.AddDeepLinkListener(startUp);
            //ServiceManager.GetService<OpenIDConnectService>().ServerListener.ListeningUri = "ats://vaffa.arcade.game";
        #endif
        Debug.Log(oidc.RedirectURI);
    }`
The StartUp class:
`[DeepLink(scheme:"ats", path: "vaffa.arcade.game")]
    private async void OpenID_DeepLinkConnector(DeepLinkArgs args)
    {
        
        if (sessionToken == null)
        {
            Debug.Log(args.Parameters["session_state"].ToString());
            Debug.Log(args.Parameters["code"].ToString());
            sessionToken = ServiceManager.GetService<OpenIDConnectService>().OidcProvider.GetAccessTokenFromCodeAsync(args.Parameters["code"].ToString(), "ats://vaffa.arcade.game").Result;
        }
        else
        {
            IUserInfo userInfo = await ServiceManager.GetService<OpenIDConnectService>().GetUserDataAsync();
            Debug.Log("Currently logged in user: " + userInfo.FullName
            + " (username: " + userInfo.Username + ") with the mail address " + userInfo.Email, this);
        }
    }`

**Bug Observed on the Following Build Targets**
- [ ] Unity editor
- [ ] PC, Mac, Standalone
- [ ] Universal Windows Platform (UWP)
- [ ] iOS
- [X ] Other (please specify): Android

Any issues in the code or the overall flow?

**Comment by BenediktHensen** [comment]
At which stage does the login flow fail? Does the app open again after the login but the method OpenID_DeepLinkConnector in your StartUp class does not execute? Or does the code execute but does not get the user data?

It is correct to create an own deep link method that is registered with the deep link service since you use a custom path "vaffa.arcade.game" in your redirection from the login page. The OpenIDConnectService by default only reacts to deep links that have an empty path or the path "login" but you can, in fact, add any other path by reacting to the deep link in the way how you have done it.

I think the error is in the OpenID_DeepLinkConnector method: You are getting the authorization code from the deep link's parameters and then directly use it on the OIDC provider implementation to get back the session token. However, this call does not go through the service itself and so the service does not receive the token. So, it will likely still show you that the user is not yet logged in when you try to get the user information as, internally, its token is still not set. The token is only stored in your custom code in the variable of your StartUp class.

To fix this, you can replace the content of your OpenID_DeepLinkConnector method with a call `ServiceManager.GetService<OpenIDConnectService>().HandleActivation(args)` and pass it the arguments of the deep link. This will trigger the service to continue the login procedure. If you have implemented all methods in your custom OIDC Provider that are given by the interface, the login flow should work. If you then call ServiceManager.GetService<OpenIDConnectService>().GetUserDataAsync(), it should give you the information about the user.

**Comment by Cyprotic** [comment]
Hey Benedikt!

Thank you for the quick reply!

Allow me to clarify the issue that we are currently having.

The problem is that when on an android we do the login we get the following log:

`Got deep link for ats://vaffa.arcade.game?session_state=9c99efda-778f-4817-9cf4-160a4229b591&code=5a261370-176d-4915-94fd-f993e6a7e2ea.9c99efda-778f-4817-9cf4-160a4229b591.ba264bcf-8c16-4ceb-9691-864a6993f350
i5.Toolkit.Core.DeepLinkAPI.DeepLinkingService:OnDeepLinkActivated(Object, String)`

This is the only log that we dont get Deeplink function call on the game.

For example this code:
[DeepLink(scheme:"ats", path: "vaffa.arcade.game")]
    private async void OpenID_DeepLinkConnector(DeepLinkArgs args)
    {
        Debug.Log("OpenID_DeepLinkConnector:" + args);
        await Task.Run(()=> ServiceManager.GetService<OpenIDConnectService>().HandleActivation(args));
        //IUserInfo userInfo = await ServiceManager.GetService<OpenIDConnectService>().GetUserDataAsync();
    }
Does not run the debug.log so we can assume it doesnt get to this point.

On our strapper we register the services as the following:
`protected override void RegisterServices()
    {
        Debug.Log("OpenIdBootStrapper");
        OpenIDConnectService oidc = new OpenIDConnectService();
        oidc.OidcProvider = new ATSOIDCProvider();
        oidc.OidcProvider.ClientData = ATSOIDCClientData.clientData;
        
        ServiceManager.RegisterService(oidc);
        #if UNITY_EDITOR
            oidc.RedirectURI = "http://127.0.0.1:8080";
            ServiceManager.GetService<OpenIDConnectService>().ServerListener.ListeningUri = "http://127.0.0.1:8080";
        #endif
        #if !UNITY_EDITOR
            oidc.RedirectURI = "ats://vaffa.arcade.game";
            DeepLinkingService service = new DeepLinkingService();
            ServiceManager.RegisterService(service);
            service.AddDeepLinkListener(startUp);
        #endif
        Debug.Log(oidc.RedirectURI);
    }`

Since now I modified it with the (ServiceManager.GetService<OpenIDConnectService>().HandleActivation(args) and still got the same behaviour Is there a wrong implementation somewhere?

Thank you in advance!

**Comment by Cyprotic** [comment]
Just wanted to update my silly mistake and if possible an update on the documentation.

I really needed the `ServiceManager.GetService<OpenIDConnectService>().HandleActivation(args)` to complete the login but also in my case I forgot to place

```
[DeepLink(scheme:"ats", path: "vaffa.arcade.game")]
private async void OpenID_DeepLinkConnector(DeepLinkArgs args)
{
Debug.Log("OpenID_DeepLinkConnector:" + args);
await Task.Run(()=> ServiceManager.GetService().HandleActivation(args));
//IUserInfo userInfo = await ServiceManager.GetService().GetUserDataAsync();
}
```

to PUBLIC async void.

But that fixed it for me, I would still place the earlier line in the docs.

Thank you for everything!

**Comment by BenediktHensen** [comment]
Ah yes, right. I will add a hint in the documentation about this that the attribute is only found on public methods.
