### ISSUE TITLE
i5 tk complains about wrong Newtonsoft.Json library, though latest is installed

### ISSUE THREAD

**Issue by fwild** [rwth-acis/i5-Toolkit-for-Unity#24]
**Describe the bug**
The toolkit complains that it is running in standard mode, as the requires Json lib is not installed, although it is installed (it complained about an earlier version 3 being installed via Unity Package Manager, but still keeps complaining when I updated it to the latest nuget package, v 13.0.3).

**To Reproduce**
log any xAPI behaviour.

**Expected behavior**
no warning

**Screenshots**

```
[i5.Toolkit.Core.ExperienceAPI.Statement] Running in standard mode since the project does not contain the required Newtonsoft JSON library for advanced features.
In standard mode you can only send straightforward Actor-Verb-Object statements.
To use advanced features, install the Newtonsoft JSON library from https://github.com/jilleJr/Newtonsoft.Json-for-Unity. 
```

**Bug Observed on the Following Build Targets**
Check applicable build targets by putting an x in-between the square brackets.
- [X ] Unity editor
- [ ] PC, Mac, Standalone
- [X] Universal Windows Platform (UWP)
- [X] iOS
- [ ] Other (please specify):

**Comment by fwild** [comment]
Obviously in MirageXR

**Comment by BenediktHensen** [comment]
This occurred since the module still relied on an old open-source mirror for the Newtonsoft library but now, Unity has its own package version of it. 
I have updated the soft dependency and now, the advanced version relies on the newer Unity package.
The module will switch to the advanced mode if the package com.unity.nuget.newtonsoft-json is installed via Unity's package manager.
